---
apiVersion: local.storage.openshift.io/v1
kind: LocalVolume
metadata:
  name: localfs-infra-alertmanager
  namespace: local-storage                                                                                                                                                                                         
spec:
  nodeSelector:
    nodeSelectorTerms:
    - matchExpressions:
      - key: kubernetes.io/hostname
        operator: In
        values:
        - infra01
        - infra02
        - infra03
  storageClassDevices:
  - storageClassName: localfs-sc-alertmanager
    volumeMode: Filesystem
    fsType: xfs 
    devicePaths:
          - /path/to/dev
...
