---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: prometheus-pv-0
  labels:
    infrapvc: prometheus
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: <PATH TO PREDEFINED VOLUME>
    server: <FQDN OF NFS SERVER>
    readOnly: false
  claimRef:
    name: prometheus-k8s-db-prometheus-k8s-0
    namespace: openshift-monitoring
...
