---
apiVersion: network.openshift.io/v1
kind: EgressNetworkPolicy
metadata:
  name: allow-192.168.1.0-24
spec:
  egress:
  - type: Allow
    to:
      cidrSelector: 192.168.1.0/24
  - type: Deny
    to:
      cidrSelector: 0.0.0.0/0
...
